<a href="https://colab.research.google.com/github/ShivamKum4r/Machine-learning/blob/main/Numpy%2Cpandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
x=np.array([1,2,3])
print(x)
m=np.array([[1,2,3],[4,5,6]])
print("Array:",m)
print("Shape: ",m.shape)
print("Size: ",m.size)
print("Type: ",m.dtype)
print("Dimension: ",m.ndim)
n=np.arange(1,30,2)
print("Arrange",n)
n=n.reshape(3,5)
print("Reshape",n)
o=np.linspace(0,4,9)
print("Linspace",o)
o.resize(3,3)
print("Resize",o)

[1 2 3]
Array: [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
Size:  6
Type:  int64
Dimension:  2
Arrange [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]
Reshape [[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]]
Linspace [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4. ]
Resize [[0.  0.5 1. ]
 [1.5 2.  2.5]
 [3.  3.5 4. ]]


In [2]:
np.ones((3,2),int)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [ ]:
np.zeros((2,3),int)

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.eye(3)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
#array=([1,1,1,2,2,2,3,3,3])
p=np.ones([2,3],int)
p
np.vstack([p,2*p])
print("Vstack",np.vstack([p,2*p]))
np.hstack([p,2*p])
print("Hstack",np.hstack([p,2*p]))
p.T
print("Transpose",p.T)
p.astype('f')
print("Astype",p.astype('f'))


Vstack [[1 1 1]
 [1 1 1]
 [2 2 2]
 [2 2 2]]
Hstack [[1 1 1 2 2 2]
 [1 1 1 2 2 2]]
Transpose [[1 1]
 [1 1]
 [1 1]]
Astype [[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
test=np.random.randint(0,10,(4,3))
print("Array",test)
test=np.random.randint(0,10,5)
print("Array",test)


Array [[3 1 4]
 [4 0 4]
 [8 5 8]
 [3 7 1]]
Array [2 5 5 1 0]


In [ ]:
np.ones((3,3),bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
np.zeros((3,3),bool)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [ ]:
m=np.array([[1,2,3],[4,5,6],[7,8,9]])
m[m%2!=0]=-1
print(m)

[[-1  2 -1]
 [ 4 -1  6]
 [-1  8 -1]]


In [ ]:
m=np.array([[1,2,3],[4,5,6],[7,8,9]])
n=np.array([[1,11,12],[4,14,15],[16,9,18]])
print(np.intersect1d(m,n))

[1 4 9]


In [ ]:
import pandas as pd
sports={
    'Archery':'Bhutan',
    'Golf':'Scotland',
    'Sumo':'Japan',
    'Taekwondo':'South Korea'
}
s=pd.Series(sports)
print("Series:\n",s)
print("\nvalues: ",s.values)
print("\nIndex: ",s.index)
s=pd.Series(['tiger','bear','moose'],index=['India','America','Canada'])
print("\nnewseries: ",s)

sports={
    'Archery':'Bhutan',
    'Golf':'Scotland',
    'Sumo':'Japan',
    'Taekwondo':'South Korea'
}
s=pd.Series(sports,index=['Golf','Sumo','Hockey'])
print("\nnewseries: ",s)



Series:
 Archery           Bhutan
Golf            Scotland
Sumo               Japan
Taekwondo    South Korea
dtype: object

values:  ['Bhutan' 'Scotland' 'Japan' 'South Korea']

Index:  Index(['Archery', 'Golf', 'Sumo', 'Taekwondo'], dtype='object')

newseries:  India      tiger
America     bear
Canada     moose
dtype: object

newseries:  Golf      Scotland
Sumo         Japan
Hockey         NaN
dtype: object


In [ ]:
import pandas as pd
s=pd.Series(np.random.randint(0,1000,10000))
s.head()

0    391
1    604
2     26
3    433
4    922
dtype: int64

In [ ]:
import pandas as pd
list=['s','h','i','v','a','m']
s=pd.Series(list)
print("Series in list:\n",s)

dict={'a':3,'b':9,'c':27,'d':81}
s=pd.Series(dict)
print("\nSeries in Dictionary:\n",s)

Series in list:
 0    s
1    h
2    i
3    v
4    a
5    m
dtype: object

Series in Dictionary:
 a     3
b     9
c    27
d    81
dtype: int64


In [ ]:
import numpy as np
import pandas as pd
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser1 = pd.Series(mylist)
ser2 = pd.Series(myarr)
ser3 = pd.Series(mydict)
#print(ser3.head())
print(ser3.tail(5))

v    21
w    22
x    23
y    24
z    25
dtype: int64


In [ ]:
ser1=pd.Series([1,2,3,4,5])
ser2=pd.Series([4,5,6,7,8])
ser1[~ser1.isin(ser2)]

0    1
1    2
2    3
dtype: int64

In [ ]:
ser1=pd.Series([1,2,3,4,5])
ser2=pd.Series([4,5,6,7,8])
ser_u=pd.Series(np.union1d(ser1,ser2))
ser_i=pd.Series(np.intersect1d(ser1,ser2))
#ser_u[ser_u.isin(ser_i)]
ser_u[~ser_u.isin(ser_i)]


3    4
4    5
dtype: int64

In [ ]:
import pandas as pd
purchase_1 = pd.Series({'Name': 'Chris',
                        'Item Purchased': 'Dog Food',
                        'Cost': 22.50})
purchase_2 = pd.Series({'Name': 'Kevyn',
                        'Item Purchased': 'Kitty Litter',
                        'Cost': 2.50})
purchase_3 = pd.Series({'Name': 'Vinod',
                        'Item Purchased': 'Bird Seed',
                        'Cost': 5.00})
df=pd.DataFrame([purchase_1,purchase_2,purchase_3],index=['Store 1','Store 1','Store 2'])
print(df)
df2=df.to_csv('store.csv')
print("\n",df.loc['Store 1'])
print("\n",df.loc['Store 2'])
print("\n",df["Name"])
print("\n",df.loc['Store 1','Cost'])
print("\n",df.T)
print("\n",df.loc[:,['Name','Cost']])
print("\n",df.drop('Store 1'))

          Name Item Purchased  Cost
Store 1  Chris       Dog Food  22.5
Store 1  Kevyn   Kitty Litter   2.5
Store 2  Vinod      Bird Seed   5.0

           Name Item Purchased  Cost
Store 1  Chris       Dog Food  22.5
Store 1  Kevyn   Kitty Litter   2.5

 Name                  Vinod
Item Purchased    Bird Seed
Cost                    5.0
Name: Store 2, dtype: object

 Store 1    Chris
Store 1    Kevyn
Store 2    Vinod
Name: Name, dtype: object

 Store 1    22.5
Store 1     2.5
Name: Cost, dtype: float64

                  Store 1       Store 1    Store 2
Name               Chris         Kevyn      Vinod
Item Purchased  Dog Food  Kitty Litter  Bird Seed
Cost                22.5           2.5        5.0

           Name  Cost
Store 1  Chris  22.5
Store 1  Kevyn   2.5
Store 2  Vinod   5.0

           Name Item Purchased  Cost
Store 2  Vinod      Bird Seed   5.0


In [ ]:
df.loc['Store 2']

Name                  Vinod
Item Purchased    Bird Seed
Cost                    5.0
Name: Store 2, dtype: object

In [ ]:
df["Name"]


Store 1    Chris
Store 1    Kevyn
Store 2    Vinod
Name: Name, dtype: object

In [ ]:
df.loc['Store 1','Cost']


Store 1    22.5
Store 1     2.5
Name: Cost, dtype: float64

In [ ]:
import pandas as pd
purchase_1 = pd.Series({'Name': 'Anuj Mehta',
                        'Tickets': 5,
                        'Amount': 1355})
purchase_2 = pd.Series({'Name': 'Sandeep Oza',
                        'Tickets': 2,
                        'Amount': 1169})
purchase_3 = pd.Series({'Name': 'Manvi Sharma',
                        'Tickets': 6,
                        'Amount': 1988})
df=pd.DataFrame([purchase_1,purchase_2,purchase_3],index=['T0001','T0002','T0003'])
print(df)

               Name  Tickets  Amount
T0001    Anuj Mehta        5    1355
T0002   Sandeep Oza        2    1169
T0003  Manvi Sharma        6    1988


In [ ]:
import pandas as pd
import numpy as np
num_series = pd.Series(np.take(list('abcdefghij'), np.random.randint(10, size=20)))
print("Original Series:")
print(num_series)
print("Frequency of each unique value of the said series.")
result = num_series.value_counts()
print(result)

Original Series:
0     h
1     d
2     g
3     c
4     d
5     j
6     d
7     d
8     h
9     e
10    e
11    a
12    c
13    e
14    b
15    f
16    j
17    b
18    d
19    b
dtype: object
Frequency of each unique value of the said series.
d    5
e    3
b    3
h    2
c    2
j    2
g    1
a    1
f    1
Name: count, dtype: int64


In [ ]:
import pandas as pd
import numpy as np
num_series = pd.Series(np.random.randint(1, 10, 10))
print("Original Series:")
print(num_series)
result = np.where(num_series % 5==0)
print("Positions of numbers that are multiples of 5:")
print(result)

Original Series:
0    4
1    5
2    3
3    5
4    3
5    4
6    1
7    2
8    8
9    5
dtype: int64
Positions of numbers that are multiples of 5:
(array([1, 3, 9]),)


In [ ]:
import pandas as pd
series1 = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
series2 = pd.Series([1, 3, 5, 7, 10])
print("Original Series1:")
print(series1)
print ("Original Series2:")
print(series2)
result = [pd.Index(series1).get_loc(i) for i in series2]
print("Positions of items of series2 in series1:")
print(result)

Original Series1:
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64
Original Series2:
0     1
1     3
2     5
3     7
4    10
dtype: int64
Positions of items of series2 in series1:
[0, 2, 4, 6, 9]


In [ ]:
import pandas as pd
num_series = pd.Series(list('2390238923902390239023'))
element_pos = [0, 2, 6, 11, 21]
print("Original Series:")
print(num_series)
result = num_series.take(element_pos)
print("\nExtract items at given positions of the said series:")
print(result)

Original Series:
0     2
1     3
2     9
3     0
4     2
5     3
6     8
7     9
8     2
9     3
10    9
11    0
12    2
13    3
14    9
15    0
16    2
17    3
18    9
19    0
20    2
21    3
dtype: object

Extract items at given positions of the said series:
0     2
2     9
6     8
11    0
21    3
dtype: object
